language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-26
    - sys-img-x86-android-26
    - extra-android-m2repository

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -k sys-img-x86-android-26
  - emulator -avd test -skindir /home/travis/build/jellow-aac/Jellow-Communicator/app/src/debug/ -skin 800x1280 -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport assembledebugAndroidTest
  - ./gradlew connecteddebugAndroidTest

env:
  global:
    - TRAVIS=true
  matrix:
    - ANDROID_TARGET=android-26
    - ANDROID_TARGET=android-26

before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)